name: LastActivities

permissions:
    contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update README.md"
          MAX_LINES: 5
          COMMIT_NAME: GitHub Activity Readme